"""update_user_model_plain_password

Revision ID: a7843f8ae565
Revises: 4b4e4e5719b9
Create Date: 2025-10-13 02:39:35.713485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7843f8ae565'
down_revision = '4b4e4e5719b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add nullable password column
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    
    # Set default password for existing users (they'll need to reset)
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE users SET password = 'changeme123' WHERE password IS NULL"))
    
    # Make password non-nullable
    op.alter_column('users', 'password', nullable=False)
    
    # Drop old columns
    op.drop_index('ix_users_email', table_name='users')
    op.drop_column('users', 'email')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###

